### ISSUE TITLE
test.py is missing in the repository

### ISSUE THREAD

**Issue by dchampak** [bhimrazy/unet#2]

**Comment by bhimrazy** [comment]
Thank you, @dchampak, for raising the issue. 
Please let me know if you would be interested in contributing to this repository.

**Comment by dchampak** [comment]
Thank you for your message. I would love to contribute in any form, but due to other obligations, i am not sure if i would be able to develop code and checkin.

**Comment by bhimrazy** [comment]
> Thank you for your message. I would love to contribute in any form, but due to other obligations, i am not sure if i would be able to develop code and checkin.

Sure, No worries. @dchampak 
Please feel free to reach out, Always happy to help.
